version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
      - banditrevolvers_node_modules:/app/node_modules/
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
volumes:
  banditrevolvers_node_modules:
